######################## Paper Information ########################################
# Personal info
paper_name: "QPMeL - Quantum-Aware Classically-Trained Embeddings via Projective Metric Learning"
preprint : True
organization: Arizona State University 
sub_organization: School of Computing and Augmented Intelligence 


######################## Paper Resources ########################################

paper_pdf: https://arxiv.org/pdf/2312.01655
# supplementary_pdf: Supplementary PDF here
# code: soon # https://github.com/MPSLab-ASU/Project_Page_Template
arXiv : https://arxiv.org/abs/2312.01655
# Additional icon links

favicon: assets/images/MPS_Lab.ico

main_media:
  source: assets/images/Training.svg
  caption: |
    **QPMeL training with prototypical loss** - The QPMeL encoder produces a set of angular coordinates for the multi-modal support and query vectors. These angular coordinates are converted to Cartesian form, after which the Complex Kernel Function (CKF) is used to compute similarity to be used with a Metric Loss function. The combination of CKF and metric loss creates a ‘Quantum-Aware’ loss function. Cartesian Conversion and CKF jointly create the Projective Metric Function (PMeF).



######################## DO NOT EDIT BELOW THIS LINE ########################################

# Footer
footer_show_references: true

#sass
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript


markdown: kramdown
permalink: pretty

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "README.md",
  ]
